### ISSUE TITLE
Emulate deterministic source declaration order for injected styles

### ISSUE THREAD

**Issue by kripod** [kripod/glaze#29]
## Motivation

In CSS, source declaration order matters:

```css
.red { color: red; }
.blue { color: blue; }
```

```jsx
<p className="blue red">
  Although the 'red' className was specified after 'blue',
  this text is blue because of the source declaration order
</p>
```

This is especially important in the case of shorthand properties (e.g. `margin` instead of `margin-top`, `margin-right`, `margin-bottom` and `margin-left`), where the expected behavior is that longhands override shorthands.

## Basic example

```jsx
<p sx={{ marginLeft: 4, margin: 2 }}>
  Even without static styles, 'marginLeft' is expected to
  take precedence over 'margin'
</p>
```

## Details

As a solution, the specificity of non-shorthand properties [can be safely increased](https://csswizardry.com/2014/07/hacks-for-dealing-with-specificity/#safely-increasing-specificity) as follows:

```css
.marginLeft-4.marginLeft-4 { margin-left: 1rem; }
.margin-2 { margin: 0.5rem; }
```

Even though the `marginLeft-4` class was declared earlier, its specificity is greater than `margin-2`'s. The insertion order of dynamic rules will not matter anymore.
